version: "3.5"

services:
  nginx:
    container_name: amnorgelanding
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 6969:80
    volumes:
      - .:/var/www/html/
      - ./.config/nginx.conf:/etc/nginx/conf.d/default.conf
